# Generated by Django 4.0.3 on 2022-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('region_name', models.CharField(max_length=200)),
                ('percent_air_pollution', models.FloatField()),
                ('percent_water_pollution', models.FloatField()),
            ],
        ),
    ]
