# Generated by Django 4.0.3 on 2022-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
