# Generated by Django 4.0.3 on 2022-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_region_percent_air_pollution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='percent_air_pollution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='region',
            name='percent_water_pollution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
