# Generated by Django 4.0.3 on 2022-03-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_region_percent_air_pollution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='percent_air_pollution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='percent_water_pollution',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='year',
            field=models.IntegerField(),
        ),
    ]
